install:
- ps: $env:LAST_TAG = git describe --abbrev=0 --tags --exclude "*-dev"
- ps: $env:TAG_NUMBER = $env:LAST_TAG.Substring($env:LAST_TAG.IndexOf('v') + 1)
- ps: if ($env:APPVEYOR_REPO_TAG -ne $True){ $env:TAG_NUMBER = $env:TAG_NUMBER + "." + $env:APPVEYOR_BUILD_NUMBER } else { $env:TAG_NUMBER = $env:TAG_NUMBER + "." + 0 }

version: 1.0.{build}
image: Visual Studio 2019
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(TAG_NUMBER)'
  package_version: '$(TAG_NUMBER)'
  assembly_version: '$(TAG_NUMBER)'
  file_version: '$(TAG_NUMBER)'
  informational_version: '$(TAG_NUMBER)'
  
build:
  parallel: true
  verbosity: minimal
  project: fivem-vstancer.sln
  
before_build:
- nuget restore

after_build:
- cmd: md %APPVEYOR_BUILD_FOLDER%\dist\vstancer
- cmd: move /Y %APPVEYOR_BUILD_FOLDER%\dist\*.* %APPVEYOR_BUILD_FOLDER%\dist\vstancer
- cmd: move /Y %APPVEYOR_BUILD_FOLDER%\VStancer.Client\bin\%CONFIGURATION%\net452\VStancer.Client.net.dll %APPVEYOR_BUILD_FOLDER%\dist\vstancer
- cmd: move /Y %APPVEYOR_BUILD_FOLDER%\VStancer.Client\bin\%CONFIGURATION%\net452\MenuAPI.dll %APPVEYOR_BUILD_FOLDER%\dist\vstancer
- cmd: move /Y %APPVEYOR_BUILD_FOLDER%\VStancer.Client\bin\%CONFIGURATION%\net452\Newtonsoft.Json.dll %APPVEYOR_BUILD_FOLDER%\dist\vstancer
- 7z a vstancer-v%TAG_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\dist\*

artifacts:
- path: vstancer-v$(TAG_NUMBER).zip
  name: vstancer

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: vstancer $(APPVEYOR_REPO_TAG_NAME)
  auth_token: 
    secure: koH1kqQLiJXw2cH24CMO1v9OA/RZ/HKeFZA8RSKOznBMsIvodL4HhzKPciA4qyfE
  draft: true
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
